In [2]:
import numpy as np

In [7]:
my_list = [1,2,3,4,5,6]
my_list

[1, 2, 3, 4, 5, 6]

In [8]:
my_list

[1, 2, 3, 4, 5, 6]

In [9]:
a = np.array(my_list)

In [10]:
print(a)

1

In [7]:
my_list%2
#it throws an error. we cannot iterate 
#through the list to find out which are the off numbers present inside a list

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [8]:
a%2
#numpy is fastest package for mathematical operations- optimised memory allocation

array([1, 0, 1, 0, 1, 0], dtype=int32)

In [ ]:
#2D array

In [11]:
#multi dimensional arrays

my_matrix = [[1,2,3],[4,'hello',6],[7,8,9]]

In [12]:
my_matrix

[[1, 2, 3], [4, 'hello', 6], [7, 8, 9]]

In [29]:
a = np.array(my_matrix)
print(a)
print(type(a))
#numpy.array is a function that returns a numpy.ndarray. There is no object type numpy.array.

[['1' '2' '3']
 ['4' 'hello' '6']
 ['7' '8' '9']]
<class 'numpy.ndarray'>


In [28]:
#converting array to list
a.tolist()

[['1', '2', '3'], ['4', 'hello', '6'], ['7', '8', '9']]

In [21]:
#working with dimensions
#1-D array

a = np.array([2,3,4,5])
print(a)
print(a.ndim) #gives the number of dimension whether a 1D array or 2D array
print(a.size) #gives the number of elements

[2 3 4 5]
1
4


In [24]:
#working with dimensions
#2-D array

a = np.array([[2,3],[4,5]])
print(a)
print(a.ndim)#gives the number of dimension whether a 1D array or 2D array
print(a.shape) #gives the shape of the array
print(a.size) #gives the number of elements

[[2 3]
 [4 5]]
2
(2, 2)
4


In [25]:
#working with dimensions
#3-D array

a = np.array([[[2,3],[4,5]]])
print(a)
print(a.ndim) #gives the number of dimension whether a 1D array or 2D array
print(a.size) #gives the number of elements
print(a.shape)

[[[2 3]
  [4 5]]]
3
4
(1, 2, 2)


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [22]:
np.arange(0,10,2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0,10,5000)

array([0.00000000e+00, 2.00040008e-03, 4.00080016e-03, ...,
       9.99599920e+00, 9.99799960e+00, 1.00000000e+01])

In [5]:
np.arange(0,13,4)

array([ 0,  4,  8, 12])

### zeros and ones

Generate arrays of zeros or ones

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [10]:
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [26]:
np.zeros((5,5))
#passing as a tuple

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [26]:
np.zeros([5,5])
#passing as a lost

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.ones(3)

array([ 1.,  1.,  1.])

In [10]:
np.ones((3,3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones(4)*5

array([5., 5., 5., 5.])

In [4]:
np.full([2,4],-45)

array([[-45, -45, -45, -45],
       [-45, -45, -45, -45]])

In [30]:
#3D matrix of zeros
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### linspace
Return evenly spaced numbers over a specified interval.

In [20]:
np.linspace(0,1,10)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [16]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## eye

Creates an identity matrix

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [18]:
np.random.rand(5)
#values between 0 and 1

array([0.27301971, 0.0967285 , 0.84762956, 0.54291515, 0.6812381 ])

In [46]:
np.random.rand(5,5)

array([[ 0.66660768,  0.87589888,  0.12421056,  0.65074126,  0.60260888],
       [ 0.70027668,  0.85572434,  0.8464595 ,  0.2735416 ,  0.10955384],
       [ 0.0670566 ,  0.83267738,  0.9082729 ,  0.58249129,  0.12305748],
       [ 0.27948423,  0.66422017,  0.95639833,  0.34238788,  0.9578872 ],
       [ 0.72155386,  0.3035422 ,  0.85249683,  0.30414307,  0.79718816]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [48]:
np.random.randn(2)

array([-0.27954018,  0.90078368])

In [32]:
np.random.randint(1,10,size=(4,5,3))

array([[[9, 4, 2],
        [8, 5, 6],
        [2, 6, 3],
        [1, 9, 6],
        [6, 4, 6]],

       [[9, 2, 5],
        [3, 2, 6],
        [5, 7, 4],
        [7, 1, 4],
        [7, 9, 8]],

       [[4, 3, 3],
        [2, 1, 6],
        [3, 5, 8],
        [4, 7, 2],
        [4, 2, 2]],

       [[8, 7, 7],
        [6, 8, 4],
        [3, 8, 1],
        [8, 3, 9],
        [8, 7, 1]]])

In [12]:
np.randint(1,10,3)

AttributeError: module 'numpy' has no attribute 'randint'

In [45]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [50]:
np.random.randint(1,100)

44

In [22]:
arr1 = np.random.randint(1,100,50)
arr1

array([79, 19, 23, 79, 59, 28, 23, 58, 57, 97, 61, 40, 39,  8, 27, 35,  1,
       45, 25, 16, 17,  6, 50, 94,  2, 16, 42, 83, 52, 18, 32, 78, 95, 17,
       99, 91, 17, 84, 71, 38, 28, 73, 84, 54, 45, 27, 22,  7, 31, 28])

In [3]:
a = np.array(np.random.randint(2,10,(3,3)))
print(a)

[[3 8 6]
 [2 9 8]
 [3 9 6]]


In [4]:
a = np.array(np.random.randint(2,10,(3,3,3)))
print(a)

[[[2 3 8]
  [2 8 2]
  [4 4 9]]

 [[5 4 9]
  [7 8 4]
  [4 7 8]]

 [[3 5 6]
  [3 7 3]
  [6 9 2]]]


## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [33]:
arr1 = np.random.randint(0,50,10)
arr1

array([15, 18, 27, 10,  0, 23, 32, 23, 19,  9])

In [34]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
import numpy as np
a = np.arange(0,25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Reshape
Returns an array containing the same data with a new shape.

In [38]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
a=np.random.randint(0,1000,50)
a

array([ 20, 238,  43, 425, 600, 525, 326, 489, 699, 460, 189, 971, 546,
       311, 936, 269, 220, 869, 144,  74,  20,  70, 322, 849, 962, 308,
       651, 430, 927,  14, 740, 141, 186, 408,  80, 736, 220, 492, 835,
       333, 207, 370, 393, 973,   6, 417, 523, 606, 825,  41])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [40]:
arr1

array([15, 18, 27, 10,  0, 23, 32, 23, 19,  9])

In [41]:
a.max()

973

In [42]:
a.argmax()

43

In [43]:
a.min()

6

In [44]:
a.argmin()

44

## Shape

Shape is an attribute that arrays have (not a method):

In [45]:
# Vector
arr.shape

(25,)

In [49]:
# Notice the two sets of brackets
arr.reshape(25,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr1.reshape(5,10)

array([[79, 19, 23, 79, 59, 28, 23, 58, 57, 97],
       [61, 40, 39,  8, 27, 35,  1, 45, 25, 16],
       [17,  6, 50, 94,  2, 16, 42, 83, 52, 18],
       [32, 78, 95, 17, 99, 91, 17, 84, 71, 38],
       [28, 73, 84, 54, 45, 27, 22,  7, 31, 28]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [75]:
arr.dtype

dtype('int64')